### ISSUE TITLE
glog 日志打印过多

### ISSUE THREAD

**Issue by Dudiao137** [childe/healer#13]
在gohangout中，使用glog的默认级别，info日志文件中出现大量如下日志。

![2020-03-27_14-01](https://user-images.githubusercontent.com/22877368/77726806-c50fa000-7033-11ea-813b-e7a822366e11.png)

建议修改日志级别，将无关日志不要打印。

**Comment by childe** [comment]
谢谢。刚刚看到，明儿去处理



---原始邮件---
发件人: "Ots Wang"<notifications@github.com&gt;
发送时间: 2020年3月27日(周五) 下午2:04
收件人: "childe/healer"<healer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [childe/healer] glog 日志打印过多 (#13)




 
在gohangout中，使用glog的默认级别，info日志文件中出现大量如下日志。
 

 
建议修改日志级别，将无关日志不要打印。

**Comment by childe** [comment]
这个是刷新 Kafka 集群的 Meta 信息时打印的, 默认5分钟打印一条日志, 我个人觉得还可以吧, 暂时还是放在 Info 级别吧.
