### ISSUE TITLE
use of closed network connection

### ISSUE THREAD

**Issue by XuHandsome** [childe/healer#27]
## 表象
E0403 10:27:31.638795       1 broker.go:241] write tcp 172.16.201.32:55248->192.168.2.2:9092: use of closed network connection
E0403 10:27:31.638872       1 brokers.go:267] get metadata of [test-topic] from 192.168.2.2:9092 error: requst of 3(7) to 10.88.11.142:9092 error: write tcp 172.16.201.32:55248->10.88.11.142:9092: use of closed network connection

## 场景
1. kafka单机部署， topic单分片时未出现
2. kafka三节点kraft集群部署， topic三分片，出现错误，经过排查网络没有问题

**Comment by XuHandsome** [comment]
找到了kafka-go项目中这个(issue)[https://github.com/segmentio/kafka-go/issues/726]，不知道是不是一样的情况

**Comment by childe** [comment]
duplicated with https://github.com/childe/gohangout/issues/239
