### ISSUE TITLE
group认证失败

### ISSUE THREAD

**Issue by guobinchn** [childe/healer#7]
在使用gohangout时，启动服务后日志报如下大量错误：
I0103 16:49:58.393766  136330 group_consumer.go:167] try to join group xxxx
I0103 16:49:58.393936  136330 group_consumer.go:190] join xxxx error: Not authorized to access group: Group authorization failed.

我的配置如下：
inputs:
    - Kafka:
        codec: json
        topic:
            nginxlog: 1
        consumer_settings:
            bootstrap.servers: "1.1.1.1:9092"
            group.id:  xxxx
            client.id: nginxlogabc
            FromBeginning: true

**Comment by childe** [comment]
@guobinchn 先问一下, 你们是用的哪一种SASL?  一共有下面四种方式.

GSSAPI (Kerberos), PLAIN, SCRAM or OAUTHBEARER

**Comment by guobinchn** [comment]
我们目前采用的PLAIN方式。

**Comment by childe** [comment]
截止到 fb223075244fe1ff68184c0e035f8f43af8e2f24 , 已经添加了plain的认证. 
(tools里面几个自带的工具还没来得及添加, 但不影响做为库使用了.
